name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy_resources:
        description: 'Destroy AWS resources created by Terraform'
        required: true
        default: 'true'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.destroy_resources == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

      - name: Read Terraform output
        id: read_terraform_output
        run: echo "::set-output name=terraform_output::$(cat terraform-output.txt)"

      - name: Terraform destroy
        run: terraform destroy -auto-approve -var "resource_info=${{ steps.read_terraform_output.outputs.terraform_output }}"
