name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Docker-Ec2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: true  # Bu, hata olduğunda işlemi durdurmaz ve devam eder.
                                                      
      - name: Copy Terraform State Files
        run: |
          mkdir -p terraform-state
          cp -R ./*.tfstate ./terraform-state/
          cp -R ./*.pem ./terraform-state/
          terraform output > terraform-outputs.txt
          cp terraform-outputs.txt ./terraform-state/
        continue-on-error: true  # Bu, hata olduğunda işlemi durdurmaz ve devam eder.
          
      - name: Commit and Push Terraform State Changes
        run: |
          git clone git@github.com:Herr-Aksoy/Terra-Githup-Delet.git
          cp -r ./terraform-state ./Terra-Githup-Delet/
          cd Terra-Githup-Delet
          git config --global user.email "mat.aksoy06@gmail.com"
          git config --global user.name "Herr-Aksoy"
          git add .
          git commit -m "Add Terraform state files"
          git push origin main
        continue-on-error: true  # Bu, hata olduğunda işlemi durdurmaz ve devam eder.
      
      - name: Terraform Destroy if Apply failed
        if: failure()
        run: terraform destroy -auto-approve






